import React from 'react';
import { Users, MessageCircle, Calendar, Trophy, ArrowRight } from 'lucide-react';
import { Button } from './ui/button';
import familyPlanning from '../assets/family_planning.jpg';

const Community = () => {
  const communityFeatures = [
    {
      icon: <Users className="w-6 h-6" />,
      title: 'Faith-Led Entrepreneurs',
      description: 'Connect with like-minded believers who are building wealth with integrity'
    },
    {
      icon: <MessageCircle className="w-6 h-6" />,
      title: 'Daily Support & Accountability',
      description: 'Get answers to your questions and stay motivated with daily community interaction'
    },
    {
      icon: <Calendar className="w-6 h-6" />,
      title: 'Weekly Live Calls',
      description: 'Join Manu for live Q&A sessions, training, and community celebrations'
    },
    {
      icon: <Trophy className="w-6 h-6" />,
      title: 'Success Stories & Wins',
      description: 'Celebrate victories together and learn from each other\'s breakthroughs'
    }
  ];

  const communityStats = [
    { number: '1,000+', label: 'Active Members' },
    { number: '$2.3M+', label: 'Generated by Community' },
    { number: '95%', label: 'Satisfaction Rate' },
    { number: '24/7', label: 'Community Support' }
  ];

  return (
    <section id="community" className="py-20 bg-muted">
      <div className="container mx-auto px-4">
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Join the WealthBuilders Community
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            You don't have to build wealth alone. Join a community of faith-led entrepreneurs 
            who are committed to building generational wealth with integrity.
          </p>
        </div>

        {/* Main Content */}
        <div className="grid lg:grid-cols-2 gap-12 items-center mb-16">
          {/* Left Column - Image */}
          <div className="flex justify-center">
            <img 
              src={familyPlanning} 
              alt="WealthBuilders Community" 
              className="w-full max-w-md rounded-lg shadow-lg"
            />
          </div>

          {/* Right Column - Content */}
          <div className="space-y-8">
            <div>
              <h3 className="text-3xl font-bold mb-4">
                More Than Just a Course - It's a Movement
              </h3>
              <p className="text-muted-foreground mb-6">
                When you join WealthBuilders, you're not just getting access to training and resources. 
                You're joining a family of believers who understand that wealth building and faith 
                aren't mutually exclusive.
              </p>
            </div>

            {/* Features */}
            <div className="space-y-6">
              {communityFeatures.map((feature, index) => (
                <div key={index} className="flex items-start gap-4">
                  <div className="p-2 bg-primary rounded-lg text-white flex-shrink-0">
                    {feature.icon}
                  </div>
                  <div>
                    <h4 className="font-semibold mb-1">{feature.title}</h4>
                    <p className="text-muted-foreground text-sm">{feature.description}</p>
                  </div>
                </div>
              ))}
            </div>

            <Button className="btn-primary px-8 py-3 text-lg font-semibold rounded-lg">
              Join Our Community Today
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
          </div>
        </div>

        {/* Community Stats */}
        <div className="bg-card p-8 rounded-lg shadow-lg mb-16">
          <h3 className="text-2xl font-bold text-center mb-8">Community Impact</h3>
          <div className="grid md:grid-cols-4 gap-6">
            {communityStats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="text-3xl font-bold text-primary mb-2">{stat.number}</div>
                <div className="text-sm text-muted-foreground">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Community Guidelines */}
        <div className="bg-card p-8 rounded-lg shadow-lg mb-16">
          <h3 className="text-2xl font-bold text-center mb-8">Our Community Values</h3>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl">🙏</span>
              </div>
              <h4 className="font-semibold mb-2">Faith-Centered</h4>
              <p className="text-muted-foreground text-sm">
                We honor God in everything we do and support each other's spiritual growth
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl">🤝</span>
              </div>
              <h4 className="font-semibold mb-2">Supportive</h4>
              <p className="text-muted-foreground text-sm">
                We lift each other up, celebrate wins, and provide encouragement during challenges
              </p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                <span className="text-2xl">💡</span>
              </div>
              <h4 className="font-semibold mb-2">Action-Oriented</h4>
              <p className="text-muted-foreground text-sm">
                We focus on implementation and results, not just theory and discussion
              </p>
            </div>
          </div>
        </div>

        {/* Testimonials */}
        <div className="grid md:grid-cols-2 gap-8">
          <div className="bg-card p-6 rounded-lg shadow-lg">
            <p className="text-muted-foreground mb-4 italic">
              "The community is what makes WealthBuilders special. I've never been part of a group 
              where people genuinely care about your success and hold you accountable to your values."
            </p>
            <div>
              <div className="font-semibold">Jennifer R.</div>
              <div className="text-sm text-muted-foreground">Marketing Professional, Ohio</div>
            </div>
          </div>
          <div className="bg-card p-6 rounded-lg shadow-lg">
            <p className="text-muted-foreground mb-4 italic">
              "Finally found my tribe! These are people who understand that you can be successful 
              in business while staying true to your faith. The support has been incredible."
            </p>
            <div>
              <div className="font-semibold">Michael T.</div>
              <div className="text-sm text-muted-foreground">Pastor & Entrepreneur, Georgia</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Community;

