import React from 'react';
import { ArrowRight, Clock, Users, Trophy } from 'lucide-react';
import { Button } from './ui/button';

const FinalCTA = () => {
  const urgencyPoints = [
    {
      icon: <Clock className="w-6 h-6" />,
      title: 'Limited Time Offer',
      description: 'Special pricing ends soon - save $20/month on WBU membership'
    },
    {
      icon: <Users className="w-6 h-6" />,
      title: 'Community Growing Fast',
      description: 'Join 1,000+ members who are already building wealth with integrity'
    },
    {
      icon: <Trophy className="w-6 h-6" />,
      title: 'Proven Results',
      description: '$2.3M+ generated by our community using The FAITH Code system'
    }
  ];

  return (
    <section className="py-20 bg-gradient-to-r from-primary to-accent text-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Your Financial Freedom Journey Starts Today
          </h2>
          <p className="text-xl mb-8 max-w-3xl mx-auto">
            You've read the stories. You've seen the results. You know The FAITH Code works. 
            The only question left is: Are you ready to take action?
          </p>
        </div>

        {/* Urgency Points */}
        <div className="grid md:grid-cols-3 gap-8 mb-12">
          {urgencyPoints.map((point, index) => (
            <div key={index} className="text-center">
              <div className="flex justify-center mb-4">
                <div className="p-3 bg-white/20 rounded-lg">
                  {point.icon}
                </div>
              </div>
              <h3 className="text-xl font-bold mb-2">{point.title}</h3>
              <p className="text-white/90">{point.description}</p>
            </div>
          ))}
        </div>

        {/* Main CTA */}
        <div className="text-center mb-12">
          <div className="bg-white/10 backdrop-blur-sm p-8 rounded-lg max-w-2xl mx-auto">
            <h3 className="text-2xl font-bold mb-4">
              Start Your 7-Day Free Trial Today
            </h3>
            <p className="text-white/90 mb-6">
              Join WealthBuilders University risk-free. If you're not completely satisfied, 
              cancel anytime during your trial period.
            </p>
            
            <div className="space-y-4">
              <Button 
                size="lg" 
                className="bg-white text-primary hover:bg-white/90 px-12 py-4 text-xl font-bold rounded-lg w-full md:w-auto"
              >
                Start Your Free Trial Now
                <ArrowRight className="w-6 h-6 ml-2" />
              </Button>
              
              <div className="text-sm text-white/80">
                ✓ 7-day free trial • ✓ Cancel anytime • ✓ No hidden fees
              </div>
            </div>
          </div>
        </div>

        {/* Alternative CTAs */}
        <div className="grid md:grid-cols-2 gap-6 max-w-4xl mx-auto">
          <div className="bg-white/10 backdrop-blur-sm p-6 rounded-lg text-center">
            <h4 className="text-lg font-bold mb-2">Not Ready to Join Yet?</h4>
            <p className="text-white/90 mb-4 text-sm">
              Start with our free AI Hustle Challenge and see results in 7 days
            </p>
            <Button 
              variant="outline" 
              className="border-white text-white hover:bg-white hover:text-primary"
            >
              Join Free Challenge
            </Button>
          </div>
          
          <div className="bg-white/10 backdrop-blur-sm p-6 rounded-lg text-center">
            <h4 className="text-lg font-bold mb-2">Want Personal Guidance?</h4>
            <p className="text-white/90 mb-4 text-sm">
              Book a 1:1 strategy call with Manu to create your custom plan
            </p>
            <Button 
              variant="outline" 
              className="border-white text-white hover:bg-white hover:text-primary"
            >
              Book Strategy Call
            </Button>
          </div>
        </div>

        {/* Final Message */}
        <div className="text-center mt-12">
          <p className="text-lg text-white/90 max-w-2xl mx-auto">
            Remember: The best time to plant a tree was 20 years ago. 
            The second best time is now. Your family's financial future is waiting.
          </p>
          <p className="text-xl font-bold mt-4">
            Act now. Be unstoppable.
          </p>
        </div>
      </div>
    </section>
  );
};

export default FinalCTA;

