import React from 'react';
import { ArrowRight, Download } from 'lucide-react';
import { Button } from './ui/button';
import heroBackground from '../assets/hero_background.png';
import professionalPortrait from '../assets/professional_portrait_1.jpeg';

const Hero = () => {
  return (
    <section id="home" className="relative min-h-screen flex items-center justify-center overflow-hidden">
      {/* Background */}
      <div 
        className="absolute inset-0 z-0"
        style={{
          backgroundImage: `url(${heroBackground})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat'
        }}
      >
        <div className="absolute inset-0 bg-gradient-to-r from-white/70 to-white/50"></div>
      </div>

      {/* Content */}
      <div className="relative z-10 container mx-auto px-4 py-20">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left Column - Text Content */}
          <div className="text-white space-y-8">
            <div className="space-y-4">
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight">
                Build Million-Dollar{' '}
                <span className="text-gradient">AI Businesses</span>{' '}
                with Integrity
              </h1>
              
              <p className="text-xl md:text-2xl text-gray-200 leading-relaxed">
                The FAITH Code system that helps everyday families create wealth through AI - 
                without compromising their values
              </p>
              
              <p className="text-lg text-gray-300">
                Join 1,000+ faith-led entrepreneurs who are building generational wealth using 
                ethical AI strategies and proven systems. No get-rich-quick schemes. 
                No compromising your values. Just real wealth building that honors God and serves your family.
              </p>
            </div>

            {/* CTA Buttons */}
            <div className="flex flex-col sm:flex-row gap-4">
             <a href="https://www.skool.com/wbu">
  <Button className="btn-primary px-8 py-4 text-lg font-semibold rounded-lg flex items-center gap-2">
    Start Your 7-Day Free Trial
    <ArrowRight size={20} />
  </Button>
</a>
              
              <Button 
                variant="outline" 
                className="px-8 py-4 text-lg font-semibold rounded-lg border-white text-white hover:bg-white hover:text-black flex items-center gap-2"
              >
                Get Free AI Hustle Handbook
                <Download size={20} />
              </Button>
            </div>

            {/* Social Proof */}
            <div className="flex items-center gap-8 pt-4">
              <div className="text-center">
                <div className="text-2xl font-bold text-primary">1,000+</div>
                <div className="text-sm text-gray-300">Active Members</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-primary">$2.3M+</div>
                <div className="text-sm text-gray-300">Generated by Community</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-primary">95%</div>
                <div className="text-sm text-gray-300">Satisfaction Rate</div>
              </div>
            </div>
          </div>

          {/* Right Column - Image */}
          <div className="flex justify-center lg:justify-end">
            <div className="relative">
              <div className="w-80 h-80 lg:w-96 lg:h-96 rounded-full overflow-hidden border-4 border-primary shadow-2xl">
                <img 
                  src={professionalPortrait} 
                  alt="Manu Alderete - WealthBuilders Founder" 
                  className="w-full h-full object-cover"
                />
              </div>
              
              {/* Floating Elements */}
              <div className="absolute -top-4 -right-4 bg-primary text-white px-4 py-2 rounded-lg font-semibold shadow-lg">
                25+ Years Experience
              </div>
              
              <div className="absolute -bottom-4 -left-4 bg-accent text-white px-4 py-2 rounded-lg font-semibold shadow-lg">
                $100M+ Managed
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Scroll Indicator */}
      <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 text-white animate-bounce">
        <div className="w-6 h-10 border-2 border-white rounded-full flex justify-center">
          <div className="w-1 h-3 bg-white rounded-full mt-2 animate-pulse"></div>
        </div>
      </div>
    </section>
  );
};

export default Hero;

